name: publish nuget

on:
  push:
    tags:
      - '*'

jobs:
  deploy_nuget:
    name: publish nuget packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - uses: olegtarasov/get-tag@v2
        name: Set tag environment variable
      - name: pack Indicia.HubSpot
        run: dotnet pack Indicia.HubSpot/Indicia.HubSpot.csproj --configuration Release -p:PackageVersion=${GIT_TAG_NAME}
      - name: push to nuget
        run: dotnet nuget push **/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --no-symbols true